import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans"; // ← この行を追加
import { GeistMono } from "geist/font/mono"; // ← この行を追加
import "./globals.css";

export const metadata: Metadata = {
  title: "周宇辰のポートフォリオ", // あなたのサイトのタイトルに合わせてください
  description: "Generated by create next app", // あなたのサイトの説明に合わせてください
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${GeistSans.variable} ${GeistMono.variable}`} // ← classNameをこのように変更
    >
      <body>{children}</body>
    </html>
  );
}
